### ISSUE TITLE
Technical: Caching CMOR for automatic checking and action perfomance. 

### ISSUE THREAD

**Issue by wolfiex** [WCRP-CMIP/CMIP6Plus_CVs#22]
It is possible to cache an environment, rather than having to recompute and install it each time. This should greatly improve the actions performance. 

Reference: https://github.com/actions/cache

An example script on how this may be approached (FOR REFERENCE ONLY)
```yaml
name: Build Conda Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Conda environment
      uses: actions/cache@v2
      with:
        path: |
          ~/.conda/pkgs
          ~/.conda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Set up Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source $HOME/miniconda/etc/profile.d/conda.sh
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda

    - name: Create Conda environment
      run: |
        conda env create -f path/to/your/environment.yml -n your_environment_name
        conda activate your_environment_name

    # ... rest of the action or build steps. 
```
